### ISSUE TITLE
Another available download link for demo-2.0.bag

### ISSUE THREAD

**Issue by Eddy-W** [cedricxie/apollo_perception_ros#7]
Hi @cedricxie, as you mentioned, the demo-2.0.bag could be downloaded at [Apollo Data Open Platform](http://data.apollo.auto/?locale=en-us&lang=en), but now it is not available.
Could you offer another download link for demo-2.0.bag or `demo-sensor-data-apollo-2.0.tar.gz`? I want to reproduce your results.

Thanks a lot.

**Comment by cedricxie** [comment]
Hi @Eddy-W , I believe the service from Baidu has resumed. Please take a look. Thank you.

**Comment by Eddy-W** [comment]
Yes. It's OK. Thanks.

**Comment by hpanyda** [comment]
Looks like Baidu has revamped the site and the demo bag is no longer available.
Can anyone share the file?

Thanks a lot.
